### PR TITLE
updated plan-feature-model.md about feature params

### PR DESCRIPTION
**Pull request by boryn**
I have written more description on how to use the features and their params.

PS. I have based the info about written "true" / "false" from `canUseFeature()` where there is:
```php
if ($featureValue === 'true') {
            // If feature value exists and has a written true value
            return true;
//

```

### CODE REVIEW

**Comment by boryn** [comment]
Was there something wrong about my changes to the docs? I wanted them to be more clear for the new users.

**Comment by bpuig** [comment]
Arg! I did not expect this to be closed after merging the branch! I'll take a look

**Comment by boryn** [comment]
And what about this mod to docs?

**Comment by bpuig** [comment]
I added partially (without the expanding) some time ago but outside the PR since this was closed by version and I messed up.

**Comment by boryn** [comment]
ok, thank you :)

**Pull request closed without merging**
