### PR TITLE
Update migration for consistency

### PR DESCRIPTION
**Pull request by boryn**
## Status
**READY**

## Migrations
YES

## Description
Just a slight change for consistency of code

### CODE REVIEW

**Comment by bpuig** [comment]
> I believe Subby v5 can still be used on Laravel v6 and v7, just without the scheduling functionality?

Right now I can't remember, but I prefer to move on and not maintain this old versions, since we are close to Laravel 9. I know Laravel 6 is LTS, but I was not here when it came out, so I think the priority would be focusing on v9, that will also be LTS.

**Comment by bpuig** [comment]
Ug, you removed `;` 🤣

**Comment by bpuig** [comment]
And I commited to the wrong branch!!! Oh my!

**Comment by boryn** [comment]
Aaaaa, sorry!!! I did the change just straight here in the github editor...

**Pull request merged**
