### PR TITLE
More generic exception while creating a Plan

### LINKED ISSUE #30: Graceful handling of double features create
When I run the below code twice (or just try to create the feature with an existing tag)

```php
$user->subscription('primary')->features()->create(
            [
                'tag'                 => 'pictures_per_social_profile',
                'name'                => 'Pictures per social profile',
                'value'               => 30,
                'sort_order'          => 10,
                'resettable_period'   => 1,
                'resettable_interval' => 'month'
            ]
        );
```

I get:
_SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-pictures_per_social_profile' for key 'plan_subscription_features.plan_subscription_features_subscription_id_tag_unique' (SQL: insert into `plan_subscription_features` (`tag`, `name`, `value`, `sort_order`, `resettable_period`, `resettable_interval`, `subscription_id`, `updated_at`, `created_at`) values (pictures_per_social_profile, Pictures per social profile, 30, 10, 1, month, 1, 2021-05-13 06:46:21, 2021-05-13 06:46:21))_

Maybe better would be to return false as a not successful query?

The same goes for creating plan with the same tag (`$plan = Plan::create()`)

### PR DESCRIPTION
**Pull request by boryn**
I'd go with this more generic solution - we will catch any other possible problem if creation of the Plan fails.

### CODE REVIEW

**Comment by bpuig** [comment]
How do you know it failed because of tag or another field? You removed the tag check.

**Comment by boryn** [comment]
I don't know exactly because of what field it failed. Now it is more universal, it will catch any exception (even if there was for example a database connection error). Just creation of the new record failed and then we raise "our" Exception. Because of whatever reason.

**Comment by bpuig** [comment]
Yep, but the exception is explicit about a duplicate.

**Comment by boryn** [comment]
Yes, actually I think you can skip this pull release. I will give a test to beta.1 on Monday, the latest on Tuesday.

**Pull request closed without merging**
